---
- name: Install Docker, Docker Compose, and run docker-compose
  hosts: localhost
  become: yes
  vars:
    git_lfs_src_url: https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh
    apt_packages:
      - unzip

  tasks:
    - name: Install Docker
      shell: curl -fsSL https://get.docker.com | sh

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.38.2/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: "0755"

    - name: Verify Docker installation
      shell: docker --version
      register: docker_version
    - debug:
        msg: "Docker installed: {{ docker_version.stdout }}"

    - name: Verify Docker Compose installation
      shell: docker-compose --version
      register: docker_compose_version
    - debug:
        msg: "Docker Compose installed: {{ docker_compose_version.stdout }}"
   
    - name: Install AWS CLI
      ansible.builtin.shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

    - name: Install Oh-My-Bash
      ansible.builtin.shell: |
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"

    - name: Run docker-compose
      docker_compose:
        project_src: /mnt/c/JManzur/Code/ansible/ansible-pull-docker-compose
        state: present
