---
- name: Install Docker, Docker Compose, and run docker-compose
  hosts: localhost
  become: yes
  vars:
    apt_packages:
      - unzip
      - curl

  tasks:
    - name: Install Docker
      ansible.builtin.shell: |
        curl -fsSL https://get.docker.com | sh

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.38.2/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: "0755"

    - name: Verify Docker installation
      shell: docker --version
      register: docker_version
    - debug:
        msg: "Docker installed: {{ docker_version.stdout }}"

    - name: Verify Docker Compose installation
      shell: docker-compose --version
      register: docker_compose_version
    - debug:
        msg: "Docker Compose installed: {{ docker_compose_version.stdout }}"
   
    - name: Install APT packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop: "{{ apt_packages }}"

    - name: Install AWS CLI
      ansible.builtin.shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip /opt/ansible-pull/awscliv2.zip
        sudo /opt/ansible-pull/aws/install

    - name: Install Oh-My-Bash
      ansible.builtin.shell: |
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"

    - name: Run docker-compose
      community.docker.docker_compose_v2:
        project_src: /opt/ansible-pull
        recreate: auto